### ISSUE TITLE
[Suggestion] Fully fold JSDoc comments

### ISSUE THREAD

**Issue by JJBocanegra** [aydgn/jsdoc-folder#1]
Hey @aydgn!

First of all, thank you very much for this extension, I just needed something like this.

 Is there a possibility to just collapse everything? I would love to be able to see just this
 ```
 /** ...
 ```

instead of this
```
/**
 * One line
 */
 ```

**Comment by aydgn** [comment]
Hey @JJBocanegra,

Thank you for your feedback. I use the second line of JSDoc as a brief explanation of what it does in one line, and I thought it would be sufficient to display just that one line by default. Since this extension was created primarily to meet my own needs, I did not include any configuration options to change this behavior. However, I will make changes so that it will fold entire comments, and this will be configurable in the settings.

**Comment by aydgn** [comment]
This feature was added in version 0.0.5.  Thanks to @JJBocanegra

**Comment by JJBocanegra** [comment]
It works!! Thanks a lot for taking the time to do it! ❤️
